# Use node_modules linker for React Native compatibility
nodeLinker: node-modules

# Improve performance on CI and local by using the global cache
enableGlobalCache: true

# Optional: reduce noise
checksumBehavior: update

# Optional: ensure immutable installs on CI (set to true in CI)
# enableImmutableInstalls: false
nodeLinker: node-modules
