import { Request, Response } from 'express';
import { customAlphabet } from 'nanoid';
import { getStorage } from '../../../../storage/storage-instance';
import { SlackIntegrationController, ChannelController } from '../../../../storage/integrations/slack/slack-controller';
import { CommunicationType } from '../../../../storage/integrations/slack/slack-types';
import { COMM_ERROR_MESSAGES, COMM_SUCCESS_MESSAGES } from '../constants';

/**
 * Slack Channel Configuration Controller
 * Handles channel configuration management for Slack integrations
 */

// Create nanoid generator for channel config IDs (shorter, URL-safe)
const nanoid = customAlphabet(
  '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-',
  21
);

// ============================================================================
// HELPERS
// ============================================================================

const getSlackController = (): SlackIntegrationController => {
  const storage = getStorage();
  return (storage as any).slackController;
};

const getChannelController = (): ChannelController => {
  const storage = getStorage();
  return (storage as any).channelController;
};

// ============================================================================
// CONTROLLERS
// ============================================================================

/**
 * Create Channel Configuration
 * POST /tenants/:tenantId/integrations/slack/channel-config
 *
 * Body: {
 *   channelData: {
 *     "development": [
 *       { "id": "C111", "name": "dev-releases" },
 *       { "id": "C222", "name": "dev-notifications" }
 *     ],
 *     "production": [
 *       { "id": "C333", "name": "prod-releases" }
 *     ]
 *   }
 * }
 *
 * Note: ID is autogenerated (nanoid)
 */
export const createChannelConfig = async (
  req: Request,
  res: Response
): Promise<any> => {
  const tenantId: string = req.params.tenantId;
  const { channelData } = req.body;

  if (!channelData || typeof channelData !== 'object') {
    return res.status(400).json({
      success: false,
      error: "'channelData' is required and must be an object"
    });
  }

  try {
    const slackController = getSlackController();
    const channelController = getChannelController();

    const integration = await slackController.findByTenant(tenantId, CommunicationType.SLACK);

    if (!integration) {
      return res.status(404).json({
        success: false,
        error: 'No Slack integration found for this tenant'
      });
    }

    const id = nanoid();

    const channelConfig = await channelController.create(
      id,
      integration.id,
      tenantId,
      channelData
    );

    return res.status(201).json({
      success: true,
      channelConfig
    });
  } catch (error: any) {
    console.error('[Slack] Error creating channel config:', error);
    return res.status(500).json({
      success: false,
      error: error.message || COMM_ERROR_MESSAGES.CREATE_CHANNEL_CONFIG_FAILED
    });
  }
};

/**
 * Get Channel Configuration by ID
 * POST /tenants/:tenantId/integrations/slack/channel-config/get
 *
 * Request body:
 * {
 *   "id": "abc123..."
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "channelConfig": {
 *     "id": "abc123...",
 *     "integrationId": "slack-int-123",
 *     "tenantId": "tenant-uuid",
 *     "channelData": {
 *       "development": [
 *         { "id": "C111", "name": "dev-releases" },
 *         { "id": "C222", "name": "dev-notifications" }
 *       ],
 *       "production": [
 *         { "id": "C333", "name": "prod-releases" }
 *       ]
 *     },
 *     "createdAt": "2025-01-01T00:00:00.000Z",
 *     "updatedAt": "2025-01-01T00:00:00.000Z"
 *   }
 * }
 */
export const getChannelConfig = async (
  req: Request,
  res: Response
): Promise<any> => {
  const { id: configId } = req.body;

  if (!configId) {
    return res.status(400).json({
      success: false,
      error: "'id' is required in request body"
    });
  }

  try {
    const channelController = getChannelController();

    const channelConfig = await channelController.findById(configId);

    if (!channelConfig) {
      return res.status(404).json({
        success: false,
        error: COMM_ERROR_MESSAGES.CHANNEL_CONFIG_NOT_FOUND
      });
    }

    return res.status(200).json({
      success: true,
      channelConfig
    });
  } catch (error: any) {
    console.error(`[Slack] Error fetching channel config ${configId}:`, error);
    return res.status(500).json({
      success: false,
      error: error.message ?? 'Failed to fetch channel configuration'
    });
  }
};

/**
 * Delete Channel Configuration by ID
 * POST /tenants/:tenantId/integrations/slack/channel-config/delete
 *
 * Request body:
 * {
 *   "id": "abc123..."
 * }
 *
 * Response (200 OK):
 * {
 *   "success": true,
 *   "message": "Channel configuration deleted successfully"
 * }
 *
 * Response (404 Not Found):
 * {
 *   "success": false,
 *   "error": "Channel configuration not found"
 * }
 */
export const deleteChannelConfig = async (
  req: Request,
  res: Response
): Promise<any> => {
  const { id: configId } = req.body;

  if (!configId) {
    return res.status(400).json({
      success: false,
      error: "'id' is required in request body"
    });
  }

  try {
    const channelController = getChannelController();

    const deleted = await channelController.delete(configId);

    if (!deleted) {
      return res.status(404).json({
        success: false,
        error: COMM_ERROR_MESSAGES.CHANNEL_CONFIG_NOT_FOUND
      });
    }

    return res.status(200).json({
      success: true,
      message: COMM_SUCCESS_MESSAGES.CHANNEL_CONFIG_DELETED
    });
  } catch (error: any) {
    console.error(`[Slack] Error deleting channel config ${configId}:`, error);
    return res.status(500).json({
      success: false,
      error: error.message ?? COMM_ERROR_MESSAGES.DELETE_CHANNEL_CONFIG_FAILED
    });
  }
};

/**
 * Update Channel Configuration - add or remove channels from a specific stage
 * POST /tenants/:tenantId/integrations/slack/channel-config/update
 *
 * Request body:
 * {
 *   "id": "abc123...",
 *   "stage": "development",
 *   "action": "add",  // or "remove"
 *   "channels": ["C111", "C222"]
 * }
 *
 * Response (200 OK):
 * {
 *   "success": true,
 *   "channelConfig": {
 *     "id": "abc123...",
 *     "integrationId": "slack-int-123",
 *     "tenantId": "tenant-uuid",
 *     "channelData": {
 *       "development": [
 *         { "id": "C111", "name": "dev-releases" },
 *         { "id": "C222", "name": "dev-notifications" },
 *         { "id": "C333", "name": "dev-alerts" }
 *       ],
 *       "production": [
 *         { "id": "C444", "name": "prod-releases" }
 *       ]
 *     },
 *     "createdAt": "2025-01-01T00:00:00.000Z",
 *     "updatedAt": "2025-01-01T00:00:00.000Z"
 *   }
 * }
 */
export const updateChannelConfig = async (
  req: Request,
  res: Response
): Promise<any> => {
  const { id: configId, stage, action, channels } = req.body;

  if (!configId) {
    return res.status(400).json({
      success: false,
      error: "'id' is required in request body"
    });
  }

  if (!stage || typeof stage !== 'string') {
    return res.status(400).json({
      success: false,
      error: "'stage' is required and must be a string"
    });
  }

  if (!action || (action !== 'add' && action !== 'remove')) {
    return res.status(400).json({
      success: false,
      error: "'action' must be either 'add' or 'remove'"
    });
  }

  if (!channels || !Array.isArray(channels) || channels.length === 0) {
    return res.status(400).json({
      success: false,
      error: "'channels' must be a non-empty array of channel objects {id, name}"
    });
  }

  try {
    const channelController = getChannelController();

    const updatedConfig = await channelController.updateStageChannels(
      configId,
      stage,
      action,
      channels
    );

    if (!updatedConfig) {
      return res.status(404).json({
        success: false,
        error: COMM_ERROR_MESSAGES.CHANNEL_CONFIG_NOT_FOUND
      });
    }

    return res.status(200).json({
      success: true,
      channelConfig: updatedConfig
    });
  } catch (error: any) {
    console.error(`[Slack] Error updating channel config ${configId}:`, error);
    return res.status(500).json({
      success: false,
      error: error.message ?? COMM_ERROR_MESSAGES.UPDATE_CHANNEL_CONFIG_FAILED
    });
  }
};
